id: 2021-01-20--trump-environmental-rollbacks-cause-80000-excess-de
date: '2021-01-20'
importance: 8
title: Trump Environmental Rollbacks Cause 80,000 Excess Deaths Per Decade
summary: Harvard researchers calculated that Trump's environmental rollbacks would
  cause 80,000 excess deaths per decade from increased air pollution, with 18,000 deaths
  from repealing the Clean Power Plan alone. The administration reversed or weakened
  over 100 environmental regulations, including mercury emissions, coal ash disposal,
  methane leaks, and vehicle fuel efficiency standards. EPA enforcement dropped 72%
  with criminal prosecutions hitting a 30-year low. The rollbacks increased greenhouse
  gas emissions by 1.8 billion tons by 2035, equivalent to Russia's annual emissions.
  Children faced increased asthma and developmental disorders from mercury exposure.
  The administration suppressed EPA scientists' climate research and removed climate
  change from government websites. Interior Secretary Bernhardt carried a card listing
  his conflicts of interest because there were so many. Courts struck down 78% of Trump's
  deregulatory actions for violating legal procedures, but damage was already done.
  The human and environmental toll represented the most destructive assault on public
  health protections in American history.
actors:
- Donald Trump
- EPA
- Scott Pruitt
- Andrew Wheeler
- David Bernhardt
- Harvard Researchers
tags:
- environmental-destruction
- public-health
- climate-change
- mass-death
- regulatory-capture
status: confirmed
sources:
- title: 'Environmental Rollbacks Under Trump Could Lead to 80,000 Extra Deaths'
  url: https://www.ehn.org/trump-environmental-rollbacks-deaths-2646687565.html
  outlet: Environmental Health News
  date: '2020-06-18'
- title: The Trump Administration Rolled Back 100+ Environmental Rules
  url: https://www.nytimes.com/interactive/2020/climate/trump-environment-rollbacks-list.html
  outlet: New York Times
  date: '2021-01-20'
- title: Harvard study on health impacts of rollbacks
  url: https://www.hsph.harvard.edu/c-change/news/economic-health-co-benefits/
  outlet: Harvard T.H. Chan School
  date: '2020-05-01'