id: 2025-06-07--dod-support-dhs-memo-and-la-deployments
date: '2025-06-07'
title: Memo authorizes DoD support to DHS; National Guard federalized; Marines deploy
  to Los Angeles
summary: A presidential memorandum authorized at least 2,000 Guard for 60 days to
  support DHS. Within days, federalized Guard and ~700 Marines supported operations
  in Los Angeles amid protests, triggering legal challenges.
location: Washington, DC
actors:
- White House
- Department of Defense
- Department of Homeland Security
tags:
- military
- domestic-deployment
- dhs
- dod
- posse-comitatus
- civil-military
- emergency-powers
citations:
- https://www.whitehouse.gov/presidential-actions/2025/06/department-of-defense-security-for-the-protection-of-department-of-homeland-security-functions
- https://www.govinfo.gov/app/details/DCPD-202500672
- https://news.usni.org/2025/06/09/700-marines-deploying-to-downtown-los-angeles
- https://www.brookings.edu/articles/how-can-the-president-put-soldiers-on-the-streets-of-los-angeles
- https://www.aila.org/presidential-memo-on-dod-security-for-the-protection-of-dhs-functions
status: confirmed
sources:
- title: Department of Defense Security for the Protection of Department of Homeland Security Functions
  url: https://www.whitehouse.gov/presidential-actions/2025/06/department-of-defense-security-for-the-protection-of-department-of-homeland-security-functions
  outlet: White House
  date: '2025-06-07'
- title: 700 Marines Deploying to Downtown Los Angeles
  url: https://news.usni.org/2025/06/09/700-marines-deploying-to-downtown-los-angeles
  outlet: USNI News
  date: '2025-06-09'
- title: How can the president put soldiers on the streets of Los Angeles?
  url: https://www.brookings.edu/articles/how-can-the-president-put-soldiers-on-the-streets-of-los-angeles
  outlet: Brookings Institution
  date: '2025-06-09'
