name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: viewer/package-lock.json
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          
      - name: Generate static API data
        run: |
          cd timeline_data
          python generate_static_api.py
          
      - name: Generate CSV and JSON exports
        run: |
          python scripts/generate_csv.py --json --viewer-dir viewer/
          echo "CSV and JSON exports generated successfully"
          
      - name: Generate YAML exports
        run: |
          python scripts/generate_yaml_export.py --viewer-dir viewer/
          echo "YAML exports generated successfully"
          
      - name: Install Node dependencies
        run: |
          cd viewer
          npm ci
          
      - name: Build viewer
        run: |
          cd viewer
          npm run build:gh-pages
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./viewer/build
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4